### ISSUE TITLE
TODO: add environmental variable based JWT secret

### ISSUE THREAD

**Issue by blaiseludvig** [blaiseludvig/stardust-backend#2]
Make the JWT secret get a proper value from an environmental variable here: 
https://github.com/blaiseludvig/stardust-backend/blob/8a75287f1d920f2ddeddc1133b5a392b1cbcfb58/src/auth/constants.ts#L1-L3
Read https://docs.nestjs.com/techniques/configuration

**Comment by hyimred** [comment]
fixed by [ffc60b2](https://github.com/blaiseludvig/stardust-backend/commit/ffc60b2bba95fa036f317f818414fa75eddaf66f)
