### ISSUE TITLE
TODO: move auth routes into auth module

### ISSUE THREAD

**Issue by blaiseludvig** [blaiseludvig/stardust-backend#5]
Move auth routes from here:
https://github.com/blaiseludvig/stardust-backend/blob/cda1239ea18292d28b5732ad0e5d0666956f0566/src/app.controller.ts#L30-L39
into the auth module

**Comment by Petermanmark** [comment]
moved by [f7275dd](https://github.com/blaiseludvig/stardust-backend/commit/f7275dda0ee5f638bf0b676c187dcaa338459ff9)
