### ISSUE TITLE
TODO: implement detection of existing users

### ISSUE THREAD

**Issue by blaiseludvig** [blaiseludvig/stardust-backend#6]
Implement logic to detect existing users here: 
https://github.com/blaiseludvig/stardust-backend/blob/cda1239ea18292d28b5732ad0e5d0666956f0566/src/users/users.service.ts#L15-L20

**Comment by Petermanmark** [comment]
implemented by [5413831](https://github.com/blaiseludvig/stardust-backend/commit/5413831e94abf092fce38b2f45f72aecc5425cfb)
