### ISSUE TITLE
TODO: remove users controller

### ISSUE THREAD

**Issue by blaiseludvig** [blaiseludvig/stardust-backend#8]
The entire users controller is unused.
https://github.com/blaiseludvig/stardust-backend/blob/56dad37b1d21619e76b3cee3c68d66485bbf90b9/src/users/users.controller.ts#L1-L36

**Comment by Petermanmark** [comment]
removed by [001b80a](https://github.com/blaiseludvig/stardust-backend/commit/001b80adc5d70ac6a2a2b3e154c4e7c197d68723)
